name: robsonjunior.dev production

on:
  push:
    branches:
      - azion

jobs:
  deploy:
    name: Azion Technologies Production
    runs-on: ubuntu-latest
    steps:
      - name: Download Azion CLI
        run: apt-get install azion;

      - name: getting robsonjunior.dev
        uses: actions/checkout@v3
        with:
          repository: robsongajunior/robsonjunior.dev
          ref: azion
          path: '.'
          clean: true
          fetch-depth: '0'

      - name: configuring nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1

      - name: installing project dependencies
        run: npm install;

    #   - name: syntax checking
    #     run: npm run check

      - name: building
        run: azion -t ${secrets.AZION_PERSONAL_TOKEN}; azion build;

      - name: edge-storage-deploy
        run: azion deploy;
